/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AutoComplete: typeof import('primevue/autocomplete')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    ConfirmDialog: typeof import('primevue/confirmdialog')['default']
    Drawer: typeof import('primevue/drawer')['default']
    Form: typeof import('@primevue/forms/form')['default']
    HomeTopBar: typeof import('./src/components/HomeTopBar.vue')['default']
    Message: typeof import('primevue/message')['default']
    Paginator: typeof import('primevue/paginator')['default']
    ProgressBar: typeof import('primevue/progressbar')['default']
    RadioButton: typeof import('primevue/radiobutton')['default']
    RadioButtonGroup: typeof import('primevue/radiobuttongroup')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Skeleton: typeof import('primevue/skeleton')['default']
    Slider: typeof import('primevue/slider')['default']
    Toast: typeof import('primevue/toast')['default']
    ViewerTopBar: typeof import('./src/components/ViewerTopBar.vue')['default']
  }
}

// For TSX support
declare global {
  const AutoComplete: typeof import('primevue/autocomplete')['default']
  const Button: typeof import('primevue/button')['default']
  const Card: typeof import('primevue/card')['default']
  const ConfirmDialog: typeof import('primevue/confirmdialog')['default']
  const Drawer: typeof import('primevue/drawer')['default']
  const Form: typeof import('@primevue/forms/form')['default']
  const HomeTopBar: typeof import('./src/components/HomeTopBar.vue')['default']
  const Message: typeof import('primevue/message')['default']
  const Paginator: typeof import('primevue/paginator')['default']
  const ProgressBar: typeof import('primevue/progressbar')['default']
  const RadioButton: typeof import('primevue/radiobutton')['default']
  const RadioButtonGroup: typeof import('primevue/radiobuttongroup')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const Skeleton: typeof import('primevue/skeleton')['default']
  const Slider: typeof import('primevue/slider')['default']
  const Toast: typeof import('primevue/toast')['default']
  const ViewerTopBar: typeof import('./src/components/ViewerTopBar.vue')['default']
}